jobs:
- name: development
  max_in_flight: 1
  plan:
    - get: dataworks-aws-data-egress
      trigger: true
    - .: (( inject meta.plan.terraform-bootstrap ))
    - .: (( inject meta.plan.get-al2-hardened-ami ))
    - .: (( inject meta.plan.terraform-apply ))
    - .: (( inject meta.plan.terraform-plan ))
