jobs:
  - name: dataworks-aws-data-egress-pr
    plan:
      - get: dataworks-aws-data-egress-pr
        trigger: true
        version: every
      - put: dataworks-aws-data-egress-pr
        params:
          path: dataworks-aws-data-egress-pr
          status: pending
      - get: dw-al2-ecs-ami
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-data-egress: dataworks-aws-data-egress-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-data-egress: dataworks-aws-data-egress-pr
        params:
          TF_WORKSPACE: qa
          DETAILED_EXITCODE: ""
          DATA_EGRESS_IMAGE_VERSION: ((data_egress_image_version))
        on_failure:
          put: dataworks-aws-data-egress-pr
          params:
            path: dataworks-aws-data-egress-pr
            status: failure
        on_success:
          put: dataworks-aws-data-egress-pr
          params:
            path: dataworks-aws-data-egress-pr
            status: success
