jobs:
- name: preprod
  max_in_flight: 1
  plan:
    - get: dataworks-aws-data-egress
      trigger: true
      passed:
        - integration
    - .: (( inject meta.plan.get-al2-hardened-ami ))
    - .: (( inject meta.plan.terraform-bootstrap ))
    - .: (( inject meta.plan.terraform-apply ))
      params:
        TF_WORKSPACE: preprod
    - .: (( inject meta.plan.terraform-plan ))
      params:
        TF_WORKSPACE: preprod
