jobs:
- name: production
  max_in_flight: 1
  plan:
  - in_parallel:
      - get: dataworks-aws-data-egress
        passed:
          - preprod
        trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
  - .: (( inject meta.plan.get-al2-hardened-ami ))
    passed:
      - preprod
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: production
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: production
