jobs:
- name: production
  max_in_flight: 1
  plan:
    - get: dataworks-aws-data-egress
      passed:
        - preprod
      trigger: true
    - .: (( inject meta.plan.get-al2-hardened-ami ))
    - .: (( inject meta.plan.terraform-bootstrap ))
      passed:
        - preprod
    - .: (( inject meta.plan.terraform-apply ))
      params:
        TF_WORKSPACE: production
    - .: (( inject meta.plan.terraform-plan ))
      params:
        TF_WORKSPACE: production
